### PR TITLE
Add Data Source for a Nomad ACL Policy.

### PR DESCRIPTION
**Pull request by ddreier**
For #82.

Needed for the Test to work:
 * Instance of Nomad with ACL enabled
 * Run the `nomad acl bootstrap` command to get a secret_id
 * Set the NOMAD_TOKEN environment variable to the secret_id

Given that there are already tests for the `nomad_acl_policy` resource that actually create and delete policies, I don't think that this should be a problem.

### CODE REVIEW

**Comment by ddreier** [comment]
Thank you for the feedback! I'm working on getting it all implemented now.

**Comment by ddreier** [comment]
I believe that I have everything addressed. Let me know if there's anything else. Thanks!

**Comment by lgfa29** [comment]
Thanks for the work @ddreier, just a couple of things left that I noticed:
* add a [menu item](https://github.com/terraform-providers/terraform-provider-nomad/blob/master/website/nomad.erb#L15) for the new data source
* the file name and test function name don't need to have `nomad` in them

**Comment by lgfa29** [comment]
I also just merged a PR that might conflict with your work, but it should be simple to fix it. Let me know if you need any help on that.

**Comment by ddreier** [comment]
@lgfa29 thanks! I have pushed those changes.

**Pull request merged**
