### PR TITLE
support Nomad 0.8.6 API

### LINKED ISSUE #46: Update the Nomad provider for new job features
### Terraform Version
0.11.8

### Affected Resource(s)
- nomad_job

### Expected Behavior
At any given time, the Nomad provider should have all the features of the latest version of Nomad (v0.8.6 at the time of this bug report)

### Actual Behavior
Terraform's Nomad provider is lagging behind.

### Important Factoids
We (and I assume many other folks) would like to codify their entire usage via Terraform.
The Terraform provider not being able to do many things makes for out-of-band activities like directly having to do `nomad plan`, `nomad run`, etc.

Using the command line is fine for folks who are very familiar with the Nomad options.
All-in-all, it is easier to direct folks to a single "interface" (i.e. Terraform, than to have to learn multiple commands and options)

Thanks and Regards,
Shantanu

### PR DESCRIPTION
**Pull request by cgbaker**
to resolve #46

### CODE REVIEW

**Comment by yellowmegaman** [comment]
Awesome) Will there be separate release?

**Comment by cgbaker** [comment]
There are just a few more merge requests I want to get in before the next release.

**Comment by csdrane** [comment]
@cgbaker 

I see that v0.11.11 was released 4 days ago, but nomad's "reschedule" jobspec still isn't supported. Will this not be available until v0.12 and if so do you have an estimate of when this will be released?

**Comment by cgbaker** [comment]
Providers are versioned and released separately from core Terraform. The v1.3.0 provider with support for Nomad 0.8.x API features will be releasing soon (hopefully this week), before Terraform v0.12.

**Pull request merged**
